In [9]:
import numpy as np
import pandas as pd

In [10]:
data = np.random.random((10,5))
#data = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv')
#data = data.select_dtypes(include='number').values
#cov = np.dot(data.T, data)

In [3]:
u,s,v = np.linalg.svd(data)
u.shape, s.shape, v.shape

((10, 10), (5,), (5, 5))

In [4]:
u.dot(np.diag(np.concatenate((s*s, np.array([0,0,0,0,0]))))).dot(np.linalg.inv(u))

array([[0.69645708, 1.2489105 , 1.23732618, 1.09524239, 0.55986412,
        0.62742254, 0.62685632, 0.5545267 , 0.69104454, 1.04312332],
       [1.2489105 , 2.48466825, 2.46194991, 2.07400089, 0.96209531,
        1.2034773 , 1.44608417, 1.12718247, 1.39336578, 1.9388964 ],
       [1.23732618, 2.46194991, 2.65269745, 2.08324318, 0.84458654,
        1.15506616, 1.44905239, 0.91950687, 1.41835205, 1.73927381],
       [1.09524239, 2.07400089, 2.08324318, 1.80022991, 0.84141114,
        0.9625008 , 1.1203703 , 0.9457585 , 1.14109955, 1.63245921],
       [0.55986412, 0.96209531, 0.84458654, 0.84141114, 0.56452614,
        0.43903313, 0.34774379, 0.54235279, 0.55738902, 0.7797697 ],
       [0.62742254, 1.2034773 , 1.15506616, 0.9625008 , 0.43903313,
        0.85460299, 0.84960296, 0.44118911, 0.63819773, 1.26129934],
       [0.62685632, 1.44608417, 1.44905239, 1.1203703 , 0.34774379,
        0.84960296, 1.17549635, 0.58569809, 0.7561654 , 1.29238264],
       [0.5545267 , 1.12718247, 0.9195068

In [5]:
np.dot(data, data.T)

array([[0.69645708, 1.2489105 , 1.23732618, 1.09524239, 0.55986412,
        0.62742254, 0.62685632, 0.5545267 , 0.69104454, 1.04312332],
       [1.2489105 , 2.48466825, 2.46194991, 2.07400089, 0.96209531,
        1.2034773 , 1.44608417, 1.12718247, 1.39336578, 1.9388964 ],
       [1.23732618, 2.46194991, 2.65269745, 2.08324318, 0.84458654,
        1.15506616, 1.44905239, 0.91950687, 1.41835205, 1.73927381],
       [1.09524239, 2.07400089, 2.08324318, 1.80022991, 0.84141114,
        0.9625008 , 1.1203703 , 0.9457585 , 1.14109955, 1.63245921],
       [0.55986412, 0.96209531, 0.84458654, 0.84141114, 0.56452614,
        0.43903313, 0.34774379, 0.54235279, 0.55738902, 0.7797697 ],
       [0.62742254, 1.2034773 , 1.15506616, 0.9625008 , 0.43903313,
        0.85460299, 0.84960296, 0.44118911, 0.63819773, 1.26129934],
       [0.62685632, 1.44608417, 1.44905239, 1.1203703 , 0.34774379,
        0.84960296, 1.17549635, 0.58569809, 0.7561654 , 1.29238264],
       [0.5545267 , 1.12718247, 0.9195068

In [6]:
((u.dot(np.diag(np.concatenate((s*s, np.array([0,0,0,0,0]))))).dot(np.linalg.inv(u)) - np.dot(data, data.T))**2).mean(axis=None)

1.1002452586295401e-30

In [7]:
v.T.dot(np.diag((s*s))).dot(np.linalg.inv(v.T))

array([[2.2210457 , 2.61593947, 1.69807934, 1.86748887, 2.20497736],
       [2.61593947, 3.91125314, 2.34946967, 2.67787237, 2.9957546 ],
       [1.69807934, 2.34946967, 2.50629727, 1.82852546, 2.27973285],
       [1.86748887, 2.67787237, 1.82852546, 2.59543114, 2.0572244 ],
       [2.20497736, 2.9957546 , 2.27973285, 2.0572244 , 2.76147943]])

In [8]:
np.dot(data.T, data)

array([[2.2210457 , 2.61593947, 1.69807934, 1.86748887, 2.20497736],
       [2.61593947, 3.91125314, 2.34946967, 2.67787237, 2.9957546 ],
       [1.69807934, 2.34946967, 2.50629727, 1.82852546, 2.27973285],
       [1.86748887, 2.67787237, 1.82852546, 2.59543114, 2.0572244 ],
       [2.20497736, 2.9957546 , 2.27973285, 2.0572244 , 2.76147943]])

In [9]:
((v.T.dot(np.diag((s*s))).dot(np.linalg.inv(v.T)) - np.dot(data.T, data))**2).mean(axis=None)

6.784203784900701e-31

In [10]:
def sort_pairs(eigenvalues, eigenvectors):
    eigenpairs = [[0,[]] for _ in range(len(eigenvalues))]
    for i in range(len(eigenvalues)):
        if eigenvalues[i] < 0:
            eigenpairs[i][0] = -1*eigenvalues[i]
            eigenpairs[i][1] = -1*eigenvectors[i]
        else:
            eigenpairs[i][0] = eigenvalues[i]
            eigenpairs[i][1] = eigenvectors[i]
    eigenpairs.sort(key=lambda eigpair: eigpair[0], reverse=True)
    eigenvalues, eigenvectors = [], []
    for eigenpair in eigenpairs:
        eigenvalues.append(eigenpair[0])
        eigenvectors.append(np.array(eigenpair[1]))
    return np.array(eigenvalues), np.array(eigenvectors)

In [11]:
L, V = np.linalg.eigh(np.dot(data, data.T))

In [12]:
print(L)
print(V)

[-1.05126879e-15 -1.42268920e-16  1.12325422e-17  1.66802958e-16
  1.15288601e-15  1.26820531e-01  3.05264353e-01  6.60127577e-01
  8.78905626e-01  1.20243886e+01]
[[-0.87468386  0.06988461 -0.11461554  0.13216944 -0.03054779  0.1368683
  -0.30287225  0.17431788  0.06510294 -0.23111901]
 [ 0.12410848  0.02906425 -0.24709873  0.03762482 -0.80385267 -0.15617669
   0.15455981  0.01540866  0.14988536 -0.45179296]
 [ 0.24232585  0.07684227 -0.27126987  0.35306659  0.38449857  0.22422428
  -0.15953145 -0.38926241  0.40351657 -0.44633316]
 [ 0.07502449 -0.35394558  0.34472555 -0.587609    0.01477472  0.4480864
  -0.07511239  0.13753832  0.18868552 -0.37922713]
 [ 0.16277813 -0.39420485  0.35030557  0.48905934  0.08119845 -0.34752889
  -0.20477237  0.49552449  0.10509223 -0.17413399]
 [ 0.01034166 -0.36964924 -0.41581897 -0.334574    0.18264374 -0.45927849
  -0.32759095 -0.16105682 -0.38326819 -0.23229767]
 [-0.27922714 -0.27960492  0.38522532  0.20216112  0.0422215  -0.08382127
   0.50302801 

In [13]:
L, V = sort_pairs(L, V)
print(L)
print(V)

[1.20243886e+01 8.78905626e-01 6.60127577e-01 3.05264353e-01
 1.26820531e-01 1.15288601e-15 1.05126879e-15 1.66802958e-16
 1.42268920e-16 1.12325422e-17]
[[ 0.2105754   0.43091335  0.13723109  0.12648426  0.01961637  0.25625037
  -0.14898643  0.18067268 -0.68794596 -0.37547672]
 [-0.06335135  0.55421678  0.3484493  -0.31383506  0.18422656 -0.54897011
   0.0032685  -0.03242339  0.26649709 -0.24805389]
 [-0.0474119   0.00545015 -0.38615437 -0.06853194  0.35884741 -0.00681602
   0.6548245   0.49596552  0.0049603  -0.2007265 ]
 [-0.27922714 -0.27960492  0.38522532  0.20216112  0.0422215  -0.08382127
   0.50302801 -0.49776935 -0.26947042 -0.26898168]
 [ 0.01034166 -0.36964924 -0.41581897 -0.334574    0.18264374 -0.45927849
  -0.32759095 -0.16105682 -0.38326819 -0.23229767]
 [ 0.16277813 -0.39420485  0.35030557  0.48905934  0.08119845 -0.34752889
  -0.20477237  0.49552449  0.10509223 -0.17413399]
 [ 0.87468386 -0.06988461  0.11461554 -0.13216944  0.03054779 -0.1368683
   0.30287225 -0.174317

In [14]:
L, V = np.linalg.eigh(np.dot(data.T, data))
print(L)
print(V)

[ 0.12682053  0.30526435  0.66012758  0.87890563 12.02438859]
[[-0.28538102  0.75203464  0.39496896 -0.19726851 -0.3976006 ]
 [-0.33896411 -0.63729867  0.24429783 -0.34259911 -0.5494526 ]
 [-0.37350509  0.00652727 -0.28779199  0.78776383 -0.39630197]
 [ 0.20237133  0.16312782 -0.77771805 -0.39695476 -0.41233083]
 [ 0.78943068 -0.04050943  0.31088341  0.25605868 -0.46145817]]


In [15]:
L, V = sort_pairs(L, V)

In [16]:
print(L)
print(V)

[12.02438859  0.87890563  0.66012758  0.30526435  0.12682053]
[[ 0.78943068 -0.04050943  0.31088341  0.25605868 -0.46145817]
 [ 0.20237133  0.16312782 -0.77771805 -0.39695476 -0.41233083]
 [-0.37350509  0.00652727 -0.28779199  0.78776383 -0.39630197]
 [-0.33896411 -0.63729867  0.24429783 -0.34259911 -0.5494526 ]
 [-0.28538102  0.75203464  0.39496896 -0.19726851 -0.3976006 ]]


In [34]:
def extract_eigenvectors(v, n_components):
    V = []
    for i in range(n_components):
        V.append(v[:,i])
    return np.array(V)

def qr_decomposition(A, extract_vectors=False):
    Q, R = np.linalg.qr(A)
    U, S, V = np.linalg.svd(R.T)
    diagonal = S*S
    oMatrix = np.dot(Q, V.T)
    if extract_vectors:
        return diagonal, extract_eigenvectors(oMatrix, len(diagonal))
    return diagonal, oMatrix 
data = np.random.random((5,2))

def qrsvd_decomposition(A, gen_HHtransposed=False, extract_vectors=False):
    Q, R = np.linalg.qr(A if gen_HHtransposed else A.T)
    U, S, V = np.linalg.svd(R.T)
    diagonal = S*S
    oMatrix = np.dot(Q, V.T)
    if extract_vectors:
        return diagonal, extract_eigenvectors(oMatrix, len(diagonal))
    return diagonal, oMatrix

In [41]:
eigval, eigvec = qrsvd_decomposition(data)

In [42]:
eigval

array([2.507825  , 0.02820331])

In [43]:
D, V = np.linalg.eigh(np.dot(data.T,data))


In [44]:
V_gen = []
for i in range(len(D)):
    V_gen.append(np.array(V[:,i]))
V = np.array(V_gen)
V.round(3)

array([[ 0.425, -0.905],
       [-0.905, -0.425]])

In [45]:
eigvec.round(3)

array([[-0.905, -0.425],
       [-0.425,  0.905]])

In [40]:
((eigvec.dot(np.diag(eigval)).dot(eigvec.T) - np.dot(data,data.T))**2).mean(axis=None)

1.9136039927431575e-32

In [ ]:
eigvec.dot(np.diag(eigval)).dot(eigvec.T)

In [ ]:
np.dot(data,data.T)

In [7]:
from sklearn.decomposition import PCA