In [4]:
import numpy as np
import pandas as pd

In [33]:
data = np.random.random((10,5))
#data = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv')
#data = data.select_dtypes(include='number').values
#cov = np.dot(data.T, data)

In [34]:
u,s,v = np.linalg.svd(data)
u.shape, s.shape, v.shape

((10, 10), (5,), (5, 5))

In [38]:
u.dot(np.diag(np.concatenate((s*s, np.array([0,0,0,0,0]))))).dot(np.linalg.inv(u))

array([[2.09499951, 1.29678794, 1.7786468 , 1.81645541, 1.62716246,
        2.23949596, 2.4380806 , 1.92397092, 0.74965793, 1.68743905],
       [1.29678794, 0.9426901 , 1.1773211 , 1.30786961, 0.98743727,
        1.44920344, 1.50481051, 1.26582368, 0.4613056 , 0.97344981],
       [1.7786468 , 1.1773211 , 1.76963986, 1.88000597, 1.79876677,
        2.09641863, 2.15684958, 1.88902258, 0.49846899, 1.38267888],
       [1.81645541, 1.30786961, 1.88000597, 2.23714084, 1.91457638,
        2.30237064, 2.33278914, 2.17661632, 0.63673806, 1.35851659],
       [1.62716246, 0.98743727, 1.79876677, 1.91457638, 2.1323648 ,
        2.08599091, 2.11389102, 1.97392395, 0.37133756, 1.28911618],
       [2.23949596, 1.44920344, 2.09641863, 2.30237064, 2.08599091,
        2.60587899, 2.75000465, 2.36021131, 0.78798682, 1.76283767],
       [2.4380806 , 1.50481051, 2.15684958, 2.33278914, 2.11389102,
        2.75000465, 3.00737974, 2.45942997, 0.90401217, 2.03084091],
       [1.92397092, 1.26582368, 1.8890225

In [39]:
np.dot(data, data.T)

array([[2.09499951, 1.29678794, 1.7786468 , 1.81645541, 1.62716246,
        2.23949596, 2.4380806 , 1.92397092, 0.74965793, 1.68743905],
       [1.29678794, 0.9426901 , 1.1773211 , 1.30786961, 0.98743727,
        1.44920344, 1.50481051, 1.26582368, 0.4613056 , 0.97344981],
       [1.7786468 , 1.1773211 , 1.76963986, 1.88000597, 1.79876677,
        2.09641863, 2.15684958, 1.88902258, 0.49846899, 1.38267888],
       [1.81645541, 1.30786961, 1.88000597, 2.23714084, 1.91457638,
        2.30237064, 2.33278914, 2.17661632, 0.63673806, 1.35851659],
       [1.62716246, 0.98743727, 1.79876677, 1.91457638, 2.1323648 ,
        2.08599091, 2.11389102, 1.97392395, 0.37133756, 1.28911618],
       [2.23949596, 1.44920344, 2.09641863, 2.30237064, 2.08599091,
        2.60587899, 2.75000465, 2.36021131, 0.78798682, 1.76283767],
       [2.4380806 , 1.50481051, 2.15684958, 2.33278914, 2.11389102,
        2.75000465, 3.00737974, 2.45942997, 0.90401217, 2.03084091],
       [1.92397092, 1.26582368, 1.8890225

In [41]:
((u.dot(np.diag(np.concatenate((s*s, np.array([0,0,0,0,0]))))).dot(np.linalg.inv(u)) - np.dot(data, data.T))**2).mean(axis=None)

6.4856076063229044e-31

In [42]:
v.T.dot(np.diag((s*s))).dot(np.linalg.inv(v.T))

array([[4.92922861, 3.33574321, 3.82133579, 3.65326499, 4.39009837],
       [3.33574321, 3.24737884, 2.63645427, 2.35847646, 3.04681967],
       [3.82133579, 2.63645427, 3.28946983, 2.85778803, 3.33943992],
       [3.65326499, 2.35847646, 2.85778803, 3.31640696, 3.5041986 ],
       [4.39009837, 3.04681967, 3.33943992, 3.5041986 , 4.24093819]])

In [43]:
np.dot(data.T, data)

array([[4.92922861, 3.33574321, 3.82133579, 3.65326499, 4.39009837],
       [3.33574321, 3.24737884, 2.63645427, 2.35847646, 3.04681967],
       [3.82133579, 2.63645427, 3.28946983, 2.85778803, 3.33943992],
       [3.65326499, 2.35847646, 2.85778803, 3.31640696, 3.5041986 ],
       [4.39009837, 3.04681967, 3.33943992, 3.5041986 , 4.24093819]])

In [44]:
((v.T.dot(np.diag((s*s))).dot(np.linalg.inv(v.T)) - np.dot(data.T, data))**2).mean(axis=None)

7.904386270314538e-30

In [45]:
def sort_pairs(eigenvalues, eigenvectors):
    eigenpairs = [[0,[]] for _ in range(len(eigenvalues))]
    for i in range(len(eigenvalues)):
        if eigenvalues[i] < 0:
            eigenpairs[i][0] = -1*eigenvalues[i]
            eigenpairs[i][1] = -1*eigenvectors[i]
        else:
            eigenpairs[i][0] = eigenvalues[i]
            eigenpairs[i][1] = eigenvectors[i]
    eigenpairs.sort(key=lambda eigpair: eigpair[0], reverse=True)
    eigenvalues, eigenvectors = [], []
    for eigenpair in eigenpairs:
        eigenvalues.append(eigenpair[0])
        eigenvectors.append(np.array(eigenpair[1]))
    return np.array(eigenvalues), np.array(eigenvectors)

In [46]:
L, V = np.linalg.eigh(np.dot(data, data.T))

In [47]:
print(L)
print(V)

[-1.44154999e-15 -3.75241766e-16  3.99297375e-17  3.27214088e-16
  1.07147821e-15  9.29941717e-02  2.42144322e-01  4.68755482e-01
  9.89655652e-01  1.72298728e+01]
[[-6.14387414e-01  4.06923744e-04  3.30122206e-02 -1.27480526e-01
  -1.57147786e-01  5.22101392e-01 -2.29879172e-01  1.17668781e-01
   3.60080548e-01 -3.33995781e-01]
 [ 1.02458544e-01  6.71715312e-02 -7.31684759e-02  1.61851614e-01
   6.76182575e-01 -3.92227659e-02 -5.67571742e-01 -3.28291754e-01
   1.36341748e-01 -2.14888648e-01]
 [ 4.75685090e-01 -1.12477438e-01 -4.83241847e-01 -6.18275119e-02
  -4.44651322e-01  1.59854191e-01 -4.03369115e-01  9.87765228e-02
  -1.72287175e-01 -3.13548595e-01]
 [-3.55594817e-01  3.34565997e-01  2.76328027e-02  1.37172991e-01
  -3.56580285e-01 -4.17302349e-01 -5.62204519e-02 -4.73266745e-01
  -3.10447943e-01 -3.42384422e-01]
 [-7.01044895e-02  3.21366260e-01 -5.10525404e-02  2.20510343e-01
   3.30166260e-01  2.51153619e-01  1.90408372e-01  4.51641779e-01
  -5.74316562e-01 -3.13711422e-01]
 

In [48]:
L, V = sort_pairs(L, V)
print(L)
print(V)

[1.72298728e+01 9.89655652e-01 4.68755482e-01 2.42144322e-01
 9.29941717e-02 1.44154999e-15 1.07147821e-15 3.75241766e-16
 3.27214088e-16 3.99297375e-17]
[[ 8.26507729e-02  3.95163052e-01 -7.23584042e-02 -2.82351228e-01
   4.20662539e-02 -5.22997864e-01  5.59909536e-03  4.74203529e-01
   4.25044504e-01 -2.66828699e-01]
 [ 2.59235412e-01  4.29768949e-01 -2.93335333e-01  9.40891658e-02
   6.02628914e-03  3.44727897e-01  4.98602445e-01 -3.91929315e-01
   3.44937875e-01 -1.14579664e-01]
 [-8.60960496e-02 -3.93192365e-01 -1.98010614e-01 -6.45167650e-01
   2.70327261e-01 -7.37254347e-02  3.17729268e-01 -2.12019013e-01
  -1.85807838e-01 -3.51563600e-01]
 [-1.26606121e-02 -5.21617762e-01 -5.21716142e-02  6.05717085e-01
  -1.11005582e-02 -2.05964333e-01  2.70643136e-01  1.05990347e-01
   2.48345285e-01 -4.11628455e-01]
 [ 4.15673867e-01  9.24410221e-03  7.89590092e-01 -1.20745262e-01
  -9.59255174e-02  1.51255157e-01  7.73375830e-03 -7.74369543e-02
   2.77786283e-03 -3.88528009e-01]
 [ 6.143874

In [49]:
L, V = np.linalg.eigh(np.dot(data.T, data))
print(L)
print(V)

[ 0.09299417  0.24214432  0.46875548  0.98965565 17.2298728 ]
[[ 0.64313274  0.47072436 -0.28724588  0.06344207 -0.52750713]
 [ 0.05897467 -0.21940587  0.28117521 -0.85168037 -0.37942602]
 [-0.40191187 -0.3644285  -0.72927098  0.01096411 -0.41677614]
 [ 0.23996364 -0.60321281  0.41124331  0.49072172 -0.41063717]
 [-0.60314722  0.48332785  0.37077363  0.17230099 -0.4852287 ]]


In [50]:
L, V = sort_pairs(L, V)

In [51]:
print(L)
print(V)

[17.2298728   0.98965565  0.46875548  0.24214432  0.09299417]
[[-0.60314722  0.48332785  0.37077363  0.17230099 -0.4852287 ]
 [ 0.23996364 -0.60321281  0.41124331  0.49072172 -0.41063717]
 [-0.40191187 -0.3644285  -0.72927098  0.01096411 -0.41677614]
 [ 0.05897467 -0.21940587  0.28117521 -0.85168037 -0.37942602]
 [ 0.64313274  0.47072436 -0.28724588  0.06344207 -0.52750713]]


In [52]:
def qr_decomposition(A):
    X = A
    D = np.diag([1 for _ in range(A.shape[1])])
    #i = 0
    while not np.allclose(X, np.triu(X)):
        Q, R = np.linalg.qr(X)
        D = np.dot(D, Q)
        X = np.dot(R, Q)
        #i += 1
    #print(i)
    return np.diagonal(X), D

In [53]:
Q, R = np.linalg.qr(data)

In [54]:
u, s, v = np.linalg.svd(R)

In [55]:
s*s

array([17.2298728 ,  0.98965565,  0.46875548,  0.24214432,  0.09299417])

In [60]:
np.dot(Q,)

array([-0.18825274, -0.04099721,  0.12691137,  0.2000881 ,  0.2613974 ,
        0.00353216,  0.31425008,  0.0643736 , -0.50712089,  0.69161307])

In [27]:
R

array([[-1.36188546, -1.32717878],
       [ 0.        ,  0.65196699]])

In [28]:
data

array([[0.83666513, 0.89471246],
       [0.55433819, 0.03413291],
       [0.30993428, 0.69056893],
       [0.86681796, 0.95283975]])