In [1]:
import nssPCA.decomposition as decompositions

In [2]:
pca = decompositions.EigenDecomposition(axis=1)

In [3]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

In [4]:
data = datasets.load_iris()['data']
data = StandardScaler().fit_transform(data)

In [5]:
cov = np.dot(data.T, data)

In [6]:
pca.fit(cov)
pca.explained_ratio

array([0.72962445, 0.22850762, 0.03668922, 0.00517871])

In [7]:
pca.components

array([[-0.52106591,  0.26934744, -0.5804131 , -0.56485654],
       [ 0.37741762,  0.92329566,  0.02449161,  0.06694199],
       [ 0.71956635, -0.24438178, -0.14212637, -0.63427274],
       [ 0.26128628, -0.12350962, -0.80144925,  0.52359713]])

In [8]:
svd = decompositions.SVDecomposition(axis=1)

In [9]:
svd.fit(data)
svd.explained_ratio

array([0.72962445, 0.22850762, 0.03668922, 0.00517871])

In [10]:
svd.components

array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
       [-0.37741762, -0.92329566, -0.02449161, -0.06694199],
       [ 0.71956635, -0.24438178, -0.14212637, -0.63427274],
       [ 0.26128628, -0.12350962, -0.80144925,  0.52359713]])

In [11]:
qrsvd = decompositions.QRSVDecomposition(axis=1)

In [17]:
qrsvd.fit(data)
qrsvd.explained_ratio

array([0.72962445, 0.22850762, 0.03668922, 0.00517871])

In [13]:
qrsvd.components

array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
       [-0.37741762, -0.92329566, -0.02449161, -0.06694199],
       [-0.71956635,  0.24438178,  0.14212637,  0.63427274],
       [ 0.26128628, -0.12350962, -0.80144925,  0.52359713]])

In [14]:
iqr = decompositions.IterativeQRDecomposition(axis=1)

In [18]:
iqr.fit(cov)
iqr.explained_ratio

array([0.72962445, 0.22850762, 0.03668922, 0.00517871])

In [19]:
iqr.components

array([[-0.52106591,  0.26934744, -0.5804131 , -0.56485654],
       [-0.37741762, -0.92329566, -0.02449161, -0.06694199],
       [ 0.71956635, -0.24438178, -0.14212637, -0.63427274],
       [ 0.26128628, -0.12350962, -0.80144925,  0.52359713]])